backend:
  name: git-gateway
  branch: v2020
media_folder: "assets/uploads"
collections:
  - name: "Posts"
    label: "Posts"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - label: "About Page"
        name: "about"
        file: "about.md"
        fields:
          - {
              label: "Title",
              name: "title",
              widget: "hidden",
              default: "about",
            }
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "about",
            }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "index"
    label: "Index"
    files:
      - file: "_data/hero.yml"
        label: "Hero Section"
        name: "hero"
        fields:
          - label: "Billboard"
            name: "billboard"
            widget: "object"
            fields:
              - { label: "Tagline", name: "body", widget: "markdown" }
              - { label: "Button", name: "button", widget: "string" }
      - file: "_data/features.yml"
        label: "Features Section"
        name: "features"
        fields:
          - label: "Feature 1"
            name: "feature1"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Text", name: "text", widget: "markdown" }
          - label: "Feature 2"
            name: "feature2"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Text", name: "text", widget: "markdown" }
          - label: "Feature 3"
            name: "feature3"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Text", name: "text", widget: "markdown" }
      - file: "_data/pricing.yml"
        label: "Pricing Section"
        name: "pricing"
        fields:
          - label: "Basic"
            name: "basic"
            widget: "object"
            fields:
              - { label: "Price", name: "price", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - label: "Features"
                name: "features"
                widget: "list"
                allow_add: true
                field: { label: "Text", name: "text", widget: "string" }
          - label: "Pro"
            name: "pro"
            widget: "object"
            fields:
              - { label: "Price", name: "price", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - label: "Features"
                name: "features"
                widget: "list"
                allow_add: true
                field: { label: "Text", name: "text", widget: "string" }
          - label: "Business"
            name: "business"
            widget: "object"
            fields:
              - { label: "Price", name: "price", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - label: "Features"
                name: "features"
                widget: "list"
                allow_add: true
                field: { label: "Text", name: "text", widget: "string" }
      - file: "_data/faqs.yml"
        label: "FAQ Section"
        name: "faqs"
        widget: "object"
        fields:
          - label: "FAQ 1"
            name: "faq1"
            widget: "object"
            fields:
              - { label: "Question", name: "question", widget: "string" }
              - { label: "Answer", name: "answer", widget: "text" }
          - label: "FAQ 2"
            name: "faq2"
            widget: "object"
            fields:
              - { label: "Question", name: "question", widget: "string" }
              - { label: "Answer", name: "answer", widget: "text" }
          - label: "FAQ 3"
            name: "faq3"
            widget: "object"
            fields:
              - { label: "Question", name: "question", widget: "string" }
              - { label: "Answer", name: "answer", widget: "text" }