backend:
  name: git-gateway
  branch: v2020
media_folder: "assets/uploads"
collections:
  - label: "Updates"
    name: "posts"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Hero"
    name: "hero"
    files:
    - label: "Hero Section"
      file: "_data/hero.yml"
      fields:
        - label: "Billboard"
          name: "billboard"
          widget: "object"
          fields:
            - { label: "Tagline", name: "body", widget: "markdown" }
            - { label: "Button", name: "button", widget: "string" }
  - label: "Gallery"
    name: "gallery"
    files:
      - label: Gallery Section
        file: "_data/gallery.yml"
        fields:
          - label: "Gallery Items"
            name: "items"
            widget: "list"
            fields:
              - { label: Image, name: image, widget: image }
              - { label: Thumbnail, name: thumb, widget: image }
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: string }
  - label: "Features"
    name: "features"
    files:
      - label: "Features Section"
        file: "_data/features.yml"
        fields:
          - label: "Feature 1"
            name: "feature1"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Text", name: "text", widget: "markdown" }
          - label: "Feature 2"
            name: "feature2"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Text", name: "text", widget: "markdown" }
          - label: "Feature 3"
            name: "feature3"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Text", name: "text", widget: "markdown" }

  - label: "Pricing"
    name: "pricing"
    files:
      - label: "Pricing Section"
        file: "_data/pricing.yml"
        fields:
          - label: "Basic"
            name: "basic"
            widget: "object"
            fields:
              - { label: "Price", name: "price", widget: "string" }
              - { label: "Description", name: "description", widget: "text"}
              - label: "Features"
                name: "features"
                widget: "list"
                allow_add: true
                field: { label: "Text", name: "text", widget: "string" }
          - label: "Pro"
            name: "pro"
            widget: "object"
            fields:
              - { label: "Price", name: "price", widget: "string" }
              - { label: "Description", name: "description", widget: "text"}
              - label: "Features"
                name: "features"
                widget: "list"
                allow_add: true
                field: { label: "Text", name: "text", widget: "string" }
          - label: "Business"
            name: "business"
            widget: "object"
            fields:
              - { label: "Price", name: "price", widget: "string" }
              - { label: "Description", name: "description", widget: "text"}
              - label: "Features"
                name: "features"
                widget: "list"
                allow_add: true
                field: { label: "Text", name: "text", widget: "string" }
  - label: "Customers"
    name: "customers"
    files:
      - label: "Customers Section"
        file: "_data/customers.yml"
        fields:
          - label: "Customers Items"
            name: "items"
            widget: "list"
            fields:
              - { label: Logo, name: logo, widget: image }
              - { label: Customer Name, name: name, widget: string }
              - { label: Country, name: country, widget: string }
  - label: "Partners"
    name: "partners"
    files:
      - label: "Partners Section"
        file: "_data/partners.yml"
        fields:
          - label: "Partners"
            name: "items"
            widget: "list"
            fields:
              - { label: Logo, name: logo, widget: image }
              - { label: Partner's Name, name: name, widget: string }
              - { label: Sector, name: sector, widget: string }
  - label: "FAQ"
    name: "faqs"
    files:
      - label: "FAQ Section"
        file: "_data/faqs.yml"
        widget: "list"
        allow_add: true
        minimize_collapsed: true
        fields:
          - label: "FAQ 1"
            name: "faq1"
            widget: "object"
            fields:
              - { label: "Question", name: "question", widget: "string" }
              - { label: "Answer", name: "answer", widget: "text" }
          - label: "FAQ 2"
            name: "faq2"
            widget: "object"
            fields:
              - { label: "Question", name: "question", widget: "string" }
              - { label: "Answer", name: "answer", widget: "text" }
          - label: "FAQ 3"
            name: "faq3"
            widget: "object"
            fields:
              - { label: "Question", name: "question", widget: "string" }
              - { label: "Answer", name: "answer", widget: "text"}