backend:
  name: git-gateway
  branch: v2020
media_folder: "assets/uploads"
collections:
  - name: "Posts"
    label: "Posts"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - label: "About Page"
        name: "about"
        file: "about.md"
        fields:
          - {
              label: "Title",
              name: "title",
              widget: "hidden",
              default: "about",
            }
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "about",
            }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "index"
    label: "Index"
    editor:
      preview: false
    files:
      - label: "Hero Section"
        name: "hero"
        file: "_data/hero.yml"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Button", name: "button", widget: "string" }
      - label: "Features Section"
        name: "features"
        file: "_data/features.yml"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Text", name: "button", widget: "string" }
          - {
              label: "Feature List",
              name: "feature_list",
              widget: "list",
              allow_add: true
            }
